export default {
	LOAD_TODO_LIST_LOADING: "LOAD_TODO_LIST_LOADING",
	LOAD_TODO_LIST_SUCCESS: "LOAD_TODO_LIST_SUCCESS",
	LOAD_TODO_LIST_FAILURE: "LOAD_TODO_LIST_FAILURE",

	SAVE_TODO_ITEM_LOADING: "SAVE_TODO_ITEM_LOADING",
	SAVE_TODO_ITEM_SUCCESS: "SAVE_TODO_ITEM_SUCCESS",
	SAVE_TODO_ITEM_FAILURE: "SAVE_TODO_ITEM_FAILURE",

	EDIT_TODO_ITEM_LOADING: "EDIT_TODO_ITEM_LOADING",
	EDIT_TODO_ITEM_SUCCESS: "EDIT_TODO_ITEM_SUCCESS",
	EDIT_TODO_ITEM_FAILURE: "EDIT_TODO_ITEM_FAILURE",

	DELETE_TODO_ITEM_LOADING: "DELETE_TODO_ITEM_LOADING",
	DELETE_TODO_ITEM_SUCCESS: "DELETE_TODO_ITEM_SUCCESS",
	DELETE_TODO_ITEM_FAILURE: "DELETE_TODO_ITEM_FAILURE"
};
